apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-deploy
  labels:
    app: hello-world
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-pod
        image: nigelpoulton/pluralsight-docker-ci:latest
        ports:
        - containerPort: 8080
